<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Anonymyzer.ConfigEditor.Abstractions\Anonymyzer.ConfigEditor.Abstractions.csproj" />
    <ProjectReference Include="..\Anonymyzer.Configuration\Anonymyzer.Configuration.csproj" />
    <ProjectReference Include="..\Anonymyzer.DatabaseAccess\Anonymyzer.DatabaseAccess.csproj" />
    <ProjectReference Include="..\Generators\Anonymyzer.Generators.Person\Anonymyzer.Generators.Person.csproj" />
    <ProjectReference Include="..\Generators\Anonymyzer.Generators.Person.Wpf\Anonymyzer.Generators.Person.Wpf.csproj" />
    <ProjectReference Include="..\Generators\Anonymyzer.Generators.Simple\Anonymyzer.Generators.Simple.csproj" />
    <ProjectReference Include="..\Generators\Anonymyzer.Generators.Simple.Wpf\Anonymyzer.Generators.Simple.Wpf.csproj" />
    <ProjectReference Include="..\LanguagePacks\Anonymyzer.LanguagePack.Polish\Anonymyzer.LanguagePack.Polish.csproj" />
    <ProjectReference Include="..\LanguagePacks\Anonymyzer.LanguagePack.English\Anonymyzer.LanguagePack.English.csproj" />
  </ItemGroup>

</Project>
