<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Anonymyzer.ConfigEditor.Abstractions\Anonymyzer.ConfigEditor.Abstractions.csproj" />
    <ProjectReference Include="..\Anonymyzer.Generators.Address\Anonymyzer.Generators.Address.csproj" />
  </ItemGroup>

</Project>
